### ISSUE TITLE
Can we get more orbital elements?

### ISSUE THREAD

**Issue by Astrodym** [msakuta/WebGL-Orbiter#1]
I appreciate the Keplerian Orbital elements, but the one thing I cant handle is how the Periapse and Apoapse have no distance distance.

looking grrrr8 tho m8

**Comment by msakuta** [comment]
It's been 3 years since I first wrote this little WebGL application, so I have to look into the code and recall my memory, but I think adding Periapsis and Apoapsis distances won't be too difficult.

**Comment by Astrodym** [comment]
Sweet, thanks B
